"""users table

Revision ID: f3bbe709af18
Revises: 
Create Date: 2019-09-27 20:52:52.455083

"""
from alembic import op
import sqlalchemy as sa
# Use for seed
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date


# revision identifiers, used by Alembic.
revision = 'f3bbe709af18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)

    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


    # Create an ad-hoc table for the seed
    user_table = table('user',
        column('id', Integer),
        column('username', String),
        column('password', String)
    )

    op.bulk_insert(user_table,
        [
            {'username':'user1', 'password':'user1'},
            {'username':'user2', 'password':'user2'},
            {'username':'user3', 'password':'user3'}
        ]
    )


    todo_table = table('todo',
            column('id', Integer),
            column('user_id', Integer),
            column('description', String)
        )

    op.bulk_insert(todo_table,
        [
            {'user_id':'user1', 'description':'Vivamus tempus'},
            {'user_id':'user1', 'description':'lorem ac odio'},
            {'user_id':'user1', 'description':'Ut congue odio'},
            {'user_id':'user1', 'description':  'Sodales finibus'},
            {'user_id':'user1', 'description':'Accumsan nunc vitae'},
            {'user_id':'user2', 'description':'Lorem ipsum'},
            {'user_id':'user2', 'description':'In lacinia est'},
            {'user_id':'user2', 'description':'Odio varius gravida'},
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
