"""todos completed

Revision ID: 548cd533554b
Revises: b376cf586452
Create Date: 2019-09-28 00:20:34.937466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Boolean


# revision identifiers, used by Alembic.
revision = '548cd533554b'
down_revision = 'b376cf586452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('todo', 'completed')
    op.add_column('todo', sa.Column('completed', sa.Boolean()))
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
