"""todos table

Revision ID: be86aff211f2
Revises: 07a205657c19
Create Date: 2019-09-27 21:38:25.917561

"""
from alembic import op
import sqlalchemy as sa
# Use for seed
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date


# revision identifiers, used by Alembic.
revision = 'be86aff211f2'
down_revision = '07a205657c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('todo') # For testing
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Create an ad-hoc table for the seed
    todo_table = table('todo',
            column('id', Integer),
            column('user_id', Integer),
            column('description', String)
        )

    op.bulk_insert(todo_table,
        [
            {'user_id':'user1', 'description':'Vivamus tempus'},
            {'user_id':'user1', 'description':'lorem ac odio'},
            {'user_id':'user1', 'description':'Ut congue odio'},
            {'user_id':'user1', 'description':  'Sodales finibus'},
            {'user_id':'user1', 'description':'Accumsan nunc vitae'},
            {'user_id':'user2', 'description':'Lorem ipsum'},
            {'user_id':'user2', 'description':'In lacinia est'},
            {'user_id':'user2', 'description':'Odio varius gravida'},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
